defmodule PgToEctoDemo.Customer do
  use Ecto.Schema
  use PgToEcto.Schema

  # Generated by PgToEcto. Do not modify this key manually.
  @pg_to_ecto_key "pgte1:dgq9ObmSJiMCSGnaGWSkAwKLivKmFCSXMyNwWl/8joE"

  schema "customers" do
    generated_fields do
      field :email, :string
      field :name, :string
      field :active, :boolean, default: true
      field :credit_limit, :integer, default: 0
      field :audit_event_id, :integer
      has_many :invoices, PgToEctoDemo.Invoice, foreign_key: :customer_id, references: :id
    end
  end
end
