defmodule PgToEctoDemo.Invoice do
  use Ecto.Schema
  use PgToEcto.Schema

  # Generated by PgToEcto. Do not modify this key manually.
  @pg_to_ecto_key "pgte1:h+LaS50aLWsegBse0t64B+vVMWFsBllfd5S243tHirQ"

  generated_settings do
    @schema_prefix "sales"
  end

  schema "invoices" do
    generated_fields do
      field :customer_id, :integer
      field :code, :string
      field :amount, :integer, default: 0

      belongs_to :customer, PgToEctoDemo.Customer,
        foreign_key: :customer_id,
        references: :id,
        define_field: false
    end
  end
end
