defmodule PgToEctoDemo.Order do
  use Ecto.Schema
  use PgToEcto.Schema

  # Generated by PgToEcto. Do not modify this key manually.
  @pg_to_ecto_key "pgte1:zXGE1yb7og0RtKWOqtdbkZ0j32guIS9Q7el2BnRTA1Y"

  schema "orders" do
    generated_fields do
      field :customer_id, :integer
      field :delete_restrict_customer_id, :integer
      field :delete_nilify_customer_id, :integer
      field :update_nilify_customer_id, :integer
      field :external_ref, :string
      field :quantity, :integer, default: 1
      field :shipped, :boolean, default: false
      field :audit_event_id, :integer

      belongs_to :customer, PgToEctoDemo.Customer,
        foreign_key: :customer_id,
        references: :id,
        define_field: false

      belongs_to :delete_nilify_customer, PgToEctoDemo.Customer,
        foreign_key: :delete_nilify_customer_id,
        references: :id,
        define_field: false

      belongs_to :delete_restrict_customer, PgToEctoDemo.Customer,
        foreign_key: :delete_restrict_customer_id,
        references: :id,
        define_field: false

      belongs_to :update_nilify_customer, PgToEctoDemo.Customer,
        foreign_key: :update_nilify_customer_id,
        references: :id,
        define_field: false
    end
  end
end
