defmodule PostgresToEctoDemo.Customer do
  use Ecto.Schema
  use PostgresToEcto.Schema

  # Generated by PostgresToEcto. Do not modify this key manually.
  @postgres_to_ecto_key "postgreste1:i+dfG5XmImTXeR3mc7AQHydICQG/L3ZCC/4feMmULXg"

  schema "customers" do
    generated_fields do
      field :email, :string
      field :name, :string
      field :active, :boolean, default: true
      field :credit_limit, :integer, default: 0
      field :audit_event_id, :integer
      has_many :invoices, PostgresToEctoDemo.Invoice, foreign_key: :customer_id, references: :id
    end
  end
end
