defmodule PostgresToEctoDemo.Invoice do
  use Ecto.Schema
  use PostgresToEcto.Schema

  # Generated by PostgresToEcto. Do not modify this key manually.
  @postgres_to_ecto_key "postgreste1:pOyH1uXfSPK2XXWKhxqCY69wfAc1BSp1RasBhP9v/Vk"

  generated_settings do
    @schema_prefix "sales"
  end

  schema "invoices" do
    generated_fields do
      field :customer_id, :integer
      field :code, :string
      field :amount, :integer, default: 0

      belongs_to :customer, PostgresToEctoDemo.Customer,
        foreign_key: :customer_id,
        references: :id,
        define_field: false
    end
  end
end
