defmodule PostgresToEctoDemo.Order do
  use Ecto.Schema
  use PostgresToEcto.Schema

  # Generated by PostgresToEcto. Do not modify this key manually.
  @postgres_to_ecto_key "postgreste1:512NcdxrmcY337dDa4rcD7N27Txk1n9oeoWcjGRl0YA"

  schema "orders" do
    generated_fields do
      field :customer_id, :integer
      field :delete_restrict_customer_id, :integer
      field :delete_nilify_customer_id, :integer
      field :update_nilify_customer_id, :integer
      field :external_ref, :string
      field :quantity, :integer, default: 1
      field :shipped, :boolean, default: false
      field :audit_event_id, :integer

      belongs_to :customer, PostgresToEctoDemo.Customer,
        foreign_key: :customer_id,
        references: :id,
        define_field: false

      belongs_to :delete_nilify_customer, PostgresToEctoDemo.Customer,
        foreign_key: :delete_nilify_customer_id,
        references: :id,
        define_field: false

      belongs_to :delete_restrict_customer, PostgresToEctoDemo.Customer,
        foreign_key: :delete_restrict_customer_id,
        references: :id,
        define_field: false

      belongs_to :update_nilify_customer, PostgresToEctoDemo.Customer,
        foreign_key: :update_nilify_customer_id,
        references: :id,
        define_field: false
    end
  end
end
