defmodule PostgresToEctoDemo.SourceRepo.Migrations.PostgresToEcto do
  use Ecto.Migration
  use PostgresToEcto.Migration

  # Generated by PostgresToEcto. Do not modify this key manually.
  @postgres_to_ecto_key "postgreste1:UsLspQf2awDC8rJ4xQEBFV8dwzYhzakRS9DrtcK3Pnk"

  def change do
    generated_change do
      execute("CREATE SCHEMA \"sales\"", "DROP SCHEMA \"sales\"")

      create table(:customers, primary_key: false) do
        add :id, :bigserial, primary_key: true, null: false
        add :email, :text, null: false
        add :name, :text, null: false
        add :active, :boolean, null: false, default: true
        add :credit_limit, :integer, null: false, default: 0
        add :audit_event_id, :bigint, null: true
      end

      create table(:orders, primary_key: false) do
        add :id, :bigserial, primary_key: true, null: false

        add :customer_id,
            references(:customers,
              type: :bigint,
              name: "orders_customer_id_fkey",
              on_delete: :delete_all
            ),
            null: false

        add :delete_restrict_customer_id,
            references(:customers,
              type: :bigint,
              name: "orders_delete_restrict_customer_id_fkey",
              on_delete: :restrict,
              on_update: :update_all
            ),
            null: true

        add :delete_nilify_customer_id,
            references(:customers,
              type: :bigint,
              name: "orders_delete_nilify_customer_id_fkey",
              on_delete: :nilify_all,
              on_update: :restrict
            ),
            null: true

        add :update_nilify_customer_id,
            references(:customers,
              type: :bigint,
              name: "orders_update_nilify_customer_id_fkey",
              on_update: :nilify_all
            ),
            null: true

        add :external_ref, :text, null: false
        add :quantity, :integer, null: false, default: 1
        add :shipped, :boolean, null: false, default: false
        add :audit_event_id, :bigint, null: true
      end

      create table(:invoices, primary_key: false, prefix: "sales") do
        add :id, :bigserial, primary_key: true, null: false

        add :customer_id,
            references(:customers,
              type: :bigint,
              prefix: "public",
              name: "invoices_customer_id_fkey",
              on_delete: :delete_all
            ),
            null: false

        add :code, :text, null: false
        add :amount, :integer, null: false, default: 0
      end

      create unique_index(:customers, [:email], name: "customers_email_index")

      create index(:orders, [:customer_id], name: "orders_customer_id_index")

      create unique_index(:orders, [:external_ref], name: "orders_external_ref_index")

      create index(:invoices, [:customer_id], name: "invoices_customer_id_index", prefix: "sales")
    end
  end
end
